### ISSUE TITLE
List of `assignerShortName` and `assignerOrgId`

### ISSUE THREAD

**Issue by tsarquis88** [CVEProject/cvelistV5#34]
Hello.

I'm working on a software that consumes CVE data and I'd like to know if there is such a thing as a list of  `assignerShortName` and `assignerOrgId`, so that we can easily match an ID with an organization, programmatically.

From this repository, I can see that, for example:

| assignerShortName | assignerOrgId |
| --- | --- |
| canonical | cc1ad9ee-3454-478d-9317-d3e869d708bc |
| debian |79363d38-fa19-49d1-9214-5f28da3f3ac5 |
| mitre | 8254265b-2729-46b6-b9e3-3dfca2d5bfca |
| ... | ... |

I could just iterate all over this project and create the list myself but it would be nice to avoid that and use an official source (an API, for example). I saw the [List of Partners](https://www.cve.org/PartnerInformation/ListofPartners) section on the web but it doesn't seem to include the organization ID (and even if it does, web scrapping would be required to consume that).

For the case there is no such thing and it's me who has to create this list: Are these IDs going to change someday? Or are they fixed?

Thanks in advance,
and great work here, BTW.

**Comment by andrewpollock** [comment]
Hi,

There's https://www.cve.org/cve-partner-name-map.json (with the caveat of https://github.com/CVEProject/cve-website/issues/1996)

**Comment by bdalalhaljwysm** [comment]
> Hello.
> 
> I'm working on a software that consumes CVE data and I'd like to know if there is such a thing as a list of and , so that we can easily match an ID with an organization, programmatically.`assignerShortName``assignerOrgId`
> 
> From this repository, I can see that, for example:
> 
> assignerShortName	assignerOrgId
> canonical	cc1ad9ee-3454-478d-9317-d3e869d708bc
> debian	79363d38-fa19-49d1-9214-5f28da3f3ac5
> mitre	8254265b-2729-46b6-b9e3-3dfca2d5bfca
> ...	...
> I could just iterate all over this project and create the list myself but it would be nice to avoid that and use an official source (an API, for example). I saw the [List of Partners](https://www.cve.org/PartnerInformation/ListofPartners) section on the web but it doesn't seem to include the organization ID (and even if it does, web scrapping would be required to consume that).
> 
> For the case there is no such thing and it's me who has to create this list: Are these IDs going to change someday? Or are they fixed?
> 
> Thanks in advance, and great work here, BTW.

**Comment by hkong-mitre** [comment]
> > I could just iterate all over this project and create the list myself but it would be nice to avoid that and use an official source (an API, for example). I saw the [List of Partners](https://www.cve.org/PartnerInformation/ListofPartners) section on the web but it doesn't seem to include the organization ID (and even if it does, web scrapping would be required to consume that).

This is a topic that has been under discussion, but no official decisions has yet been made.

> > For the case there is no such thing and it's me who has to create this list: Are these IDs going to change someday? Or are they fixed?

The IDs are fixed and do not change.
