### ISSUE TITLE
Remove note about "Known Issues with the cvelistV5 repository" from 3/28/2023 from readme. 

### ISSUE THREAD

**Issue by superchordate** [CVEProject/cvelistV5#61]
Thanks for all the great work on this! 

I'm seeing this at https://github.com/CVEProject/cvelistV5.

> Added 3/28/2023: CVE Records published prior to 2023 may have significant publication, reserved, and update date discrepancies. As a result, this repository should not be used for CVE production metrics at this time. A fix will be forthcoming.

I'm guessing this has actually been resolved and the README just needs to be updated, because it seem like a critical issue and it was reported over a year ago.

**Comment by M-nj** [comment]
Hello, an update relating to that specific "known issue" can be found here https://github.com/CVEProject/cvelistV5/issues/41#issuecomment-2356100742
